#!/usr/bin/env escript
%% -*- erlang -*-
%%! -sasl errlog_type error -boot start_sasl

find_files(Dir, Regex, Recursive) ->
    filelib:fold_files(Dir, Regex, Recursive,
                       fun(F, Acc) -> [F | Acc] end, []).

generateErlangProto([File | Rest],Output_include_dir,Output_src_dir)->
	protobuffs_compile:generate_source (File,[{output_include_dir,Output_include_dir},{output_src_dir,Output_src_dir}]),
	generateErlangProto(Rest,Output_include_dir,Output_src_dir);
generateErlangProto([],_,_)->
	ok.

main ([Dir,Output_include_dir,Output_src_dir]) ->
  io:format("Lengh: ~p~n", [length([Dir,Output_include_dir,Output_src_dir])]),
  io:format("SString is ~p~n", [[Dir,Output_include_dir,Output_src_dir]]),
  case find_files(Dir, ".*\\.proto$",true) of
  	[]->
  		ok;
  	FoundFiles->
  		generateErlangProto(FoundFiles,Output_include_dir,Output_src_dir)
  end;
main ([]) ->
  case find_files("./", ".*\\.proto$",true) of
  	[]->
  		ok;
  	FoundFiles->
  		generateErlangProto(FoundFiles,"../include","../src")
  end;
main ([File]) ->
  protobuffs_compile:generate_source (File);
main (_) ->
  io:format ("usage: ~s <protofile>~n",
             [filename:basename (escript:script_name())]),
  halt(1).

